version: '3.4'
services: 
  gogs-db:
    image: onjin/alpine-postgres
    container_name: gogs-db
    volumes:
      - mariadb-storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gogs
      - TZ=Asia/Bangkok
    restart: always

  gogs-server:
    image: gogs/gogs
    ports:
      - "10022:22"
      - "3000:3000"
    volumes:
      - "gogs-data:/data"
    depends_on:
      - gogs-db
    restart: always

volumes:
  mariadb-storage:
  gogs-data: