version: '3.4'
services: 
  gogs-db:
    image: mariadb:10
    container_name: gogs-db
    volumes:
      - mariadb-storage:/var/lib/mysql
      - mariadb-storage:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
      - TZ=Asia/Bangkok
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=admin --execute 'SHOW DATABASES';"
      interval: 3s
      timeout: 1s
      retries: 5

volumes:
  mariadb-storage: